---
# Ipwrap filter plugin o Wrap IPv6 addresses in [ ] brackets.
- name: Set value as input list
  hosts: uma.local
  tasks:
  - name: set facts
    ansible.builtin.set_fact:
      value:
        - 192.24.2.1
        - host.fqdn
        - uma.local
        - ::1
        - 192.168.32.0/24
        - fe80::100/10
        - 42540766412265424405338506004571095040/64
        - 172.31.20.70

  - debug:
      msg: "{{ value|ansible.utils.ipaddr|ansible.utils.ipwrap }}"


  - name: set facts
    ansible.builtin.set_fact:
      value:
        - 192.24.2.1
        - host.fqdn
        - ::1
        - 192.168.32.0/24
        - fe80::100/10
        - 42540766412265424405338506004571095040/64
        - 172.31.20.70

  - debug:
      msg: "{{ value|ansible.utils.ipwrap }}"


  - name: set facts
    ansible.builtin.set_fact:
      apiserver_endpoint: 172.31.20.70

  - debug:
      msg: "{{ apiserver_endpoint |ansible.utils.ipwrap }}"
